Implemented Account endpoint
eejitcms/api pull request #3
Opened 2019-02-25 20:08 UTC by Alekaei

- [x] GET /api/account *lists all accounts*
- [x] POST /api/account *create a new account*
- [x] GET /api/account/:id *get an account with username :id*
- [x] PUT /api/account/:id *update account information*
- [x] DELETE /api/account/:id *delete an account*

2019-02-25 20:33 UTC, Alekaei commented on EejitCMS.API/Controllers/AccountController.cs
> +			search.EmailVerified = accountInput.Email == null;
Needs to be fixed to include check if search.EmailVerified is true or false

2019-02-25 21:18 UTC, ericm approved these changes

2019-02-26 14:46 UTC, jac requested changes

2019-02-26 14:46 UTC, J-Cotter commented on EejitCMS.API/Models/Account.cs
> +			reason = "Password is bellow 8 characters";
@Alekaei "below"

2019-02-26 14:49 UTC, TooFiveFive commented
smh @J-Cotter

2019-02-26 14:57 UTC, jac approved these changes

2019-02-26 14:57 UTC, merged